----------------------
--CREACION DE TABLAS--
----------------------


CREATE DATABASE SistemaGestionVentasBD
GO
USE SistemaGestionVentasBD
GO
CREATE TABLE USUARIO (
	IdUsuario INT PRIMARY KEY IDENTITY (1,1),
	NombreUsuario VARCHAR(50) NOT NULL UNIQUE,
	Contrasena VARCHAR(100) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Rol INT NOT NULL,
	Email VARCHAR(150) NOT NULL UNIQUE,
	Telefono VARCHAR(30) NULL,
	Estado BIT NOT NULL DEFAULT 1
)
go
CREATE TABLE CLIENTE (
	IdCliente INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(100) NOT NULL,
	Documento VARCHAR(20) NULL,
	Telefono VARCHAR(30) NULL,
	Email VARCHAR(150) NULL,
	Direccion VARCHAR(150) NULL,
	Estado BIT NOT NULL DEFAULT 1
)
go
CREATE TABLE MARCA (
	IdMarca INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL UNIQUE,
	Descripcion VARCHAR(150) NULL,
	Estado BIT NOT NULL DEFAULT 1
)
go
CREATE TABLE CATEGORIA (
	IdCategoria INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL UNIQUE,
	Descripcion VARCHAR(150) NULL,
	Estado BIT NOT NULL DEFAULT 1
)
go
