----------------------
--CREACION DE TABLAS--
----------------------


CREATE DATABASE SistemaGestionVentasBD
GO
USE SistemaGestionVentasBD
GO
CREATE TABLE USUARIO (
	IdUsuario INT PRIMARY KEY IDENTITY (1,1),
	NombreUsuario VARCHAR(50) NOT NULL UNIQUE,
	Contrasena VARCHAR(100) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Rol INT NOT NULL,
	Email VARCHAR(150) NOT NULL UNIQUE,
	Telefono VARCHAR(30) NULL,
	Estado BIT NOT NULL DEFAULT 1
)
go
CREATE TABLE CLIENTE (
	IdCliente INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(100) NOT NULL,
	Documento VARCHAR(20) NULL,
	Telefono VARCHAR(30) NULL,
	Email VARCHAR(150) NULL,
	Direccion VARCHAR(150) NULL,
	Estado BIT NOT NULL DEFAULT 1
)
go
CREATE TABLE MARCA (
	IdMarca INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL UNIQUE,
	Descripcion VARCHAR(150) NULL,
	Estado BIT NOT NULL DEFAULT 1
)
go
CREATE TABLE CATEGORIA (
	IdCategoria INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL UNIQUE,
	Descripcion VARCHAR(150) NULL,
	Estado BIT NOT NULL DEFAULT 1
)
go
CREATE TABLE PRODUCTO (
	IdProducto INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(250) NULL,
	UrlImagen VARCHAR(500) NULL,
	Precio DECIMAL(18,2) NOT NULL CHECK (Precio>0),
	Stock INT NOT NULL CHECK (Stock>=0),
	IdMarca INT NOT NULL,
	IdCategoria INT NOT NULL,
	Medida VARCHAR(50) NULL,
	Estado BIT NOT NULL DEFAULT 1,
	CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY (IdMarca) REFERENCES MARCA(IdMarca),
	CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA(IdCategoria)
)
go
CREATE TABLE VENTA (
	IdVenta INT PRIMARY KEY IDENTITY (1,1),
	IdCliente INT NOT NULL,
	IdUsuario INT NOT NULL,
	Fecha DATETIME NOT NULL DEFAULT GETDATE(),
	Total DECIMAL(18,2) NOT NULL CHECK (Total >= 0),
	Estado BIT NOT NULL DEFAULT 1,

	CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente),
	CONSTRAINT FK_VENTA_USUARIO FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
)
go
CREATE TABLE DETALLE_VENTA (
	IdDetalleVenta INT PRIMARY KEY IDENTITY (1,1),
	IdVenta INT NOT NULL,
	IdProducto INT NOT NULL,
	Cantidad INT NOT NULL CHECK (Cantidad > 0),
	PrecioUnitario DECIMAL(18,2) NOT NULL CHECK (PrecioUnitario > 0),

	CONSTRAINT UQ_DETALLE_VENTA_IDVENTA_IDPRODUCTO UNIQUE (IdVenta, IdProducto),
	CONSTRAINT FK_DETALLE_VENTA_VENTA FOREIGN KEY (IdVenta) REFERENCES VENTA(IdVenta),
	CONSTRAINT FK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (IdProducto) REFERENCES PRODUCTO(IdProducto)
)
go